app:
  name: "distributed-delay-queue"
  env: "local" # local, dev, prod

server:
  port: 8080
  grpc_port: 9090

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

queue:
  visibility_timeout: 5  # 5 秒没处理完，就认为 Worker 挂了
  watchdog_interval: 5   # 每 5 秒检查一次
  max_retries: 3         # 默认重试 3 次
